// AUTH
export const UPDATE_AUTH = 'UPDATE_AUTH';

// USER
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// QUESTIONS
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';
export const SAVING_COMPLETE = 'SAVING_COMPLETE';
export const SAVING_ERROR = 'SAVING_ERROR';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

// RESULTS
export const LOAD_RESULTS = 'LOAD_RESULTS';
export const RESULTS_ERROR = 'RESULTS_ERROR';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
